### PR TITLE
add Dockerfile

### LINKED ISSUE #47: Create Docker file for potential shiny proxy deployment.
Use this as [example.](https://github.com/Sage-Bionetworks/kubernetes-deployments/blob/3429364a8b6be8733d2b25e1e19f8107f014bfaf/shiny/example_shiny/Dockerfile)

@milen-sage @ychae Let's add this to sprint 7 planning.

### PR DESCRIPTION
**Pull request by andrewelamb**
fixes #47

### CODE REVIEW

**Comment by andrewelamb** [comment]
@thomasyu888 Could you take a look at the dockerfile? I've adapted from your example, but adapted it to use the renv lockfile for r dependencies, and to install a python venv + synapseclient.

What are your thoughts on venv vs conda envs?

**Review by milen-sage — APPROVED** [review]
Lean and neat! This looks like a good barebones for the shiny apps we have, especially once we get them all on the shiny modules rails and we start using the schematic's REST API instead of the package (ow you'd have to add schematic installation in here too).

@andrewelamb do you think eventually, in the long term of 9 months, we can switch to using REST API for synapse directly or do some of the PL modules require functionality that would be too much effort to replicate using straight the synapse REST services? That way we wouldn't need to worry about installing the client and worry about things like python package versions.

**Comment by andrewelamb** [comment]
@milen-sage Porjectlive uses the synapse client for three things:
 - synget for the rds files
 - oauth 
 - seeing teams from a list the user belongs to

The synget I think is fairly simple to use from the REST API. I don't know how hard it would be for the other two pieces.

**Comment by milen-sage** [comment]
Cool - both oauth and teams endpoints are straightforward. Some of the table endpoints are complicated, but we may be good to go switching to using the REST service directly.

**Comment by andrewelamb** [comment]
As of now, projectlive itself doesn't use any synapse table functions (the rds files come from files views, but that's done outside of the app)

**Comment by thomasyu888** [comment]
This looks great @andrewelamb .  Using `venv` for python dependencies is great in a container - the python 3 version will change overtime since you're using `rocker/r-base:latest` - it'll continually be updated.

**Review by thomasyu888 — APPROVED** [review]

**Pull request merged**
